language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  - BUILD_CONFIGURATION=2
  - BUILD_CONFIGURATION=3
  - BUILD_CONFIGURATION=4
  - BUILD_CONFIGURATION=5
  - BUILD_CONFIGURATION=6
  - BUILD_CONFIGURATION=7

install:
  - wget -qO- https://cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.tar.gz | tar xvz

branches:
  only:
    - master
    - development
    - /^release-.*$/

script:
  - ./cmake-2.8.12.2-Linux-i386/bin/ctest -VV -S ./cmake/usCTestScript_travis.cmake

