sudo: false

addons:
  apt:
    packages:
    - valgrind

cache:
  directories:
    - $HOME/cache

language: cpp
compiler:
  - gcc
#  - clang

env:
  global:
  - PATH=$HOME/cache/bin/:$PATH
  matrix:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  #- BUILD_CONFIGURATION=2
  #- BUILD_CONFIGURATION=3

branches:
  except:
    - coverity_scan
    - gh_pages

before_install:
  - bash install_cmake.sh

script:
  - ctest -VV -S ./cmake/usCTestScript_travis.cmake

