sudo: false

cache:
  directories:
    - $HOME/cache

language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  - PATH=$HOME/cache/bin/:$PATH
  matrix:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  - BUILD_CONFIGURATION=2
  - BUILD_CONFIGURATION=3
  - BUILD_CONFIGURATION=4
  - BUILD_CONFIGURATION=5
  - BUILD_CONFIGURATION=6
  - BUILD_CONFIGURATION=7

branches:
  only:
    - master
    - development
    - /^release-.*$/

before_install:
  - bash install_cmake.sh

script:
  - ctest -VV -S ./cmake/usCTestScript_travis.cmake

